Console.WriteLine("GitHub uchun 4-project");
Console.WriteLine("1-commit");
Console.WriteLine("2-commit");
Console.WriteLine("3-commit");
Console.WriteLine("4-commit");
Console.WriteLine("5-commit");
Console.WriteLine("6-commit");
Console.WriteLine("7-commit");
Console.WriteLine("8-commit");
Console.WriteLine("9-commit");
